cloud:
    config:
      server:
        git:
          uri: https://github.com/ayoubzoubeidi/ministere-config-repo
          force-pull: true
          default-label: main
          clone-on-start: true
          search-paths: '{application}/{profile}'
          skip-ssl-validation: true